### ISSUE TITLE
Conditional manual import

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-import-build#6]
If your production and development share the same server entry file, then you need to conditionally import `importBuild.cjs`.

There are multiple approaches.

<br/>

**1. Top-level await.**

```js
// server.js

if (process.env.NODE_ENV === 'production') {
  await import('./path/to/dist/server/importBuild.cjs')
}

// ... server code ...
```

For environments that don't support top-level await, see alternatives below.

<br/>

**2. Wrap entry code in async function.**

```js
// server.js

main()

// We wrap the entire code of server.js in an async function main()
async function main() {
  if (process.env.NODE_ENV === 'production') {
    await import('./path/to/dist/server/importBuild.cjs')
  }

  // ... server code ...
}
```

<br/>

**3. Await `import()` promise in middleware.**

```js
// server.js

const serverBuildPromise = getServerBuildPromise()

app.get('*', async (req, res, next) => {
  // Ensure import('./path/to/dist/server/importBuild.cjs') has finished
  await serverBuildPromise()
  // ... middleware ... (e.g. the middleware for vite-plugin-ssr or Telefunc)
})

function getServerBuildPromise() {
  if (process.env.NODE_ENV !== 'production') return
  let resolve
  const serverBuildPromise = new Promise((r) => { resolve = r })
  import('./path/to/dist/server/importBuild.cjs').then(() => {
    resolve()
  })
  return serverBuildPromise
}
```

**Comment by arthurgailes** [comment]
Still broken on windows. Repro updated. 

```
Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): Not a posix path: C:\[...mypath]\vite-plugin-ssr-workspace-repro\packages\boilerplate-react-ts/../../dist/boilerplate-react-ts
    at assertPosixPath (C:\[...mypath]\vite-plugin-ssr-workspace-repro\node_modules\.pnpm\vite-plugin-ssr@0.4.132_vite@4.3.9\node_modules\vite-plugin-ssr\dist\cjs\utils\filesystemPathHandling.js:23:25)
    at determineOutDir (C:\[...mypath]\vite-plugin-ssr-workspace-repro\node_modules\.pnpm\vite-plugin-ssr@0.4.132_vite@4.3.9\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js:28:50)
    at config (C:\[mypath]\vite-plugin-ssr-workspace-repro\node_modules\.pnpm\vite-plugin-ssr@0.4.132_vite@4.3.9\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\buildConfig.js:35:57)
    at runConfigHook (file:///C:/[...mypath]/vite-plugin-ssr-workspace-repro/node_modules/.pnpm/vite@4.3.9_@types+node@18.16.16/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64543:31)
    at resolveConfig (file:///C:/[...mypath]/vite-plugin-ssr-workspace-repro/node_modules/.pnpm/vite@4.3.9_@types+node@18.16.16/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64026:14)
    at build (file:///C:/[...mypath]/vite-plugin-ssr-workspace-repro/node_modules/.pnpm/vite@4.3.9_@types+node@18.16.16/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46318:20)
    at CAC.<anonymous> (file:///C:/[...mypath]/vite-plugin-ssr-workspace-repro/node_modules/.pnpm/vite@4.3.9_@types+node@18.16.16/node_modules/vite/dist/node/cli.js:812:9)
```
